version: "3"

services:
  main:
    image: order-api-docker
    ports:
      - 8081:8081
    networks:
      - mainNet

  db:
    image: mysql:8
    restart: always
    container_name: exercise-db-container
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: exercise_db
    ports:
      - 8082:8082
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - dbNet


volumes:
  db_volume:
    name: my-sql-volume

networks:
  mainNet:
    name: main.net
  dbNet:
    name: db.net

