version: "3"

services:
  main:
    image: 'order-api-docker:latest'
    container_name: app
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/exercise_db?characterEncoding=utf8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=compose-root
      - SPRING_DATASOURCE_PASSWORD=compose-1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081
    networks:
      - mainNet

  db:
    image: mysql:8
    restart: always
    container_name: exercise-db-container
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: exercise_db
    ports:
      - 8082:8082
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - dbNet

volumes:
  db_volume:
    name: my-sql-volume

networks:
  dbNet:
    name: db.net
  mainNet:
    name: main.net

