###
### Database api
### +RequestBody
POST http://localhost:8081/api2/orders/add

### +RequestBody
POST http://localhost:8081/api2/products/add

###
DELETE http://localhost:8081/api2/orders/1

###
PUT http://localhost:8081/api2/orders/8/addToOrder/3

###
DELETE http://localhost:8081/api2/orders/8/deleteFromOrder/3

###
GET http://localhost:8081/api2/products/3

###
### Main api
###
GET http://localhost:8081/api1/products/get/3

###
POST http://localhost:8081/api1/orders/add

###
DELETE http://localhost:8081/api1/orders/delete/10
###  {{id}}} ???

###
PUT http://localhost:8081/api1/orders/8/addToOrder/3

###
DELETE http://localhost:8081/api1/orders/8/deleteFromOrder/3

###
PUT http://localhost:8081/api1/orders/9/sent